name: Retrain ML Model

on:
  push:
    branches: [main]
    paths:
      - "ml/dataset.csv"

env:
  AWS_REGION: ap-south-1

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Dependencies
        working-directory: terraform/modules/lambda/python
        run: |
          pip install -r requirements.txt

      - name: Retrain Model
        run: |
          cd ml
          python train.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload model to S3
        run: |
          aws s3 cp model/model.joblib s3://ml-model-bucket-alok/model.joblib
          aws s3 cp model/vectorizer.joblib s3://ml-model-bucket-alok/vectorizer.joblib
